version: '3'
services:
    python:
        restart: always
        build: .
        container_name: python_app
        tty: true
        volumes:
            - ../src:/root/src
            - ../lib:/root/lib
