version: '3'

services:
  php:
    build:
      context: ./php/
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./php/php.ini:/etc/php.ini
      - ./httpd/httpd.conf:/etc/httpd/conf/httpd.conf
    ports:
      - 8080:80
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/volumes:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
